services:
  mongodb:
    image: mongo
    restart: always
    volumes:
      - dbdata:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: local
      MONGO_INITDB_ROOT_PASSWORD: local

  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - authdbdata:/data/db
    environment:
      - POSTGRES_PASSWORD=local
      - POSTGRES_USER=local
      - POSTGRES_DB=auth

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass local
    volumes:
      - cache:/data

  server:
    depends_on:
      - mongodb
      - postgres
      - cache
    build:
      context: .
      target: final
    ports:
      - 8000:8000

volumes:
  dbdata:
  authdbdata:
  cache:
    driver: local
