services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: local
      MONGO_INITDB_ROOT_PASSWORD: local
    healthcheck:
      test: mongo localhost:27017 --eval 'db.version()'
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
